<x-app-layout>
    <div class="max-w-7xl mx-auto p-4 md:p-6 space-y-6">
        <div class="flex flex-wrap justify-between items-center gap-4">
            <div><p class="text-xs font-semibold uppercase tracking-wide text-primary">Business overview</p><h1 class="text-2xl font-semibold text-gray-900 mt-1">Welcome, {{ auth()->user()->name }}</h1><p class="text-sm text-gray-500 mt-1">{{ today()->format('l, d M Y') }} · Your billing workspace at a glance.</p></div>
            <div class="flex flex-wrap gap-2">@can('invoices.create')<a href="{{ route('invoices.create') }}" class="bg-primary text-white rounded-lg px-4 py-2.5 text-sm font-semibold">+ Create invoice</a>@endcan
                @can('reports.view')<a href="{{ route('reports.index') }}" class="bg-white border rounded-lg px-4 py-2.5 text-sm">View reports</a>@endcan</div>
        </div>
        <section class="grid grid-cols-1 md:grid-cols-3 gap-4" aria-label="Monthly overview">
            @if($customerCount !== null)<div class="bg-white border rounded-xl p-5"><p class="text-sm text-gray-500">Customers</p><p class="text-3xl font-semibold mt-2">{{ $customerCount }}</p><p class="text-xs text-gray-400 mt-2">Active customer records</p></div>@endif
            @can('payments.view')<div class="bg-white border rounded-xl p-5"><p class="text-sm text-gray-500">Collections this month</p>@forelse($collections as $collection)<p class="text-xl font-semibold mt-2">{{ $collection->currency_code }} {{ number_format((float)$collection->amount, 2) }}</p>@empty<p class="text-sm mt-3 text-gray-400">No payments this month.</p>@endforelse<p class="text-xs text-gray-400 mt-2">Payment date · month to date</p></div>@endcan
            @if($expenses !== null)<div class="bg-white border rounded-xl p-5"><p class="text-sm text-gray-500">Expenses this month</p><p class="text-3xl font-semibold mt-2">{{ number_format((float)$expenses, 2) }}</p><p class="text-xs text-amber-700 mt-2">Currency unspecified in expense records</p></div>@endif
        </section>
        @can('invoices.view')
            <section class="bg-white border rounded-xl p-5"><h2 class="font-semibold">Invoice performance</h2><p class="text-xs text-gray-500 mt-1">All-time issued invoices · draft/cancelled excluded · currencies never combined</p>
                <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">@forelse($invoiceMetrics as $metric)<div class="border rounded-lg p-4"><p class="text-primary font-semibold">{{ $metric->currency_code }}</p><dl class="space-y-3 mt-3"><div class="flex justify-between"><dt class="text-sm text-gray-500">Invoices</dt><dd>{{ $metric->invoice_count }}</dd></div><div><dt class="text-xs text-gray-500">Total invoiced</dt><dd class="text-xl font-semibold">{{ number_format((float)$metric->invoiced, 2) }}</dd></div><div><dt class="text-xs text-gray-500">Outstanding</dt><dd class="text-xl font-semibold">{{ number_format((float)$metric->outstanding, 2) }}</dd></div></dl></div>@empty<p class="text-sm text-gray-500">No issued invoices yet. Start by creating a draft.</p>@endforelse</div>
            </section>
            <div class="grid grid-cols-1 xl:grid-cols-3 gap-5">
                <section class="xl:col-span-2 bg-white border rounded-xl overflow-hidden"><div class="flex justify-between p-5 border-b"><h2 class="font-semibold">Recent invoices</h2><a href="{{ route('invoices.index') }}" class="text-primary text-sm">View all</a></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50 text-gray-500"><tr><th class="text-left p-4">Invoice / customer</th><th class="text-left p-4">Status</th><th class="text-right p-4">Total</th></tr></thead><tbody>@forelse($recentInvoices as $invoice)<tr class="border-t"><td class="p-4"><a class="font-semibold text-primary" href="{{ route('invoices.show', $invoice) }}">{{ $invoice->invoice_number }}</a><p class="text-xs text-gray-500 mt-1">{{ $invoice->customer?->name ?? 'Unavailable customer' }}</p></td><td class="p-4"><span class="inline-flex rounded-full bg-gray-100 px-2 py-1 text-xs">{{ ucfirst($invoice->status) }}</span></td><td class="p-4 text-right whitespace-nowrap">{{ $invoice->currency_code }} {{ number_format((float)$invoice->total_amount, 2) }}</td></tr>@empty<tr><td colspan="3" class="p-6 text-gray-500 text-center">No invoices yet.</td></tr>@endforelse</tbody></table></div></section>
                <section class="bg-white border rounded-xl p-5"><h2 class="font-semibold">Overdue follow-ups</h2><p class="text-xs text-gray-500 mt-1">Oldest due dates first · unpaid active invoices</p><div class="space-y-4 mt-4">@forelse($overdueInvoices as $invoice)<a href="{{ route('invoices.show', $invoice) }}" class="block border rounded-lg p-3 hover:bg-gray-50"><p class="text-primary font-semibold text-sm">{{ $invoice->invoice_number }}</p><p class="text-xs text-gray-500 mt-1">{{ $invoice->customer?->name }} · Due {{ $invoice->due_date->format('d M Y') }}</p><p class="text-sm font-semibold text-red-600 mt-2">{{ $invoice->currency_code }} {{ number_format((float)$invoice->outstanding, 2) }}</p></a>@empty<p class="text-sm text-gray-500">No overdue balances to follow up.</p>@endforelse</div></section>
            </div>
        @endcan
        @if($customerCount === null && $expenses === null && !auth()->user()->can('invoices.view') && !auth()->user()->can('payments.view'))<div class="bg-white border rounded-xl p-6"><h2 class="font-semibold">Your workspace is ready</h2><p class="text-sm text-gray-500 mt-2">Use the navigation menu to access the tools assigned to your role. Contact an administrator if you need more access.</p></div>@endif
    </div>
</x-app-layout>
